name: Inference_Server

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker registry
        run: echo "${{ secrets.DOCKER_REGISTRY_PASSWORD }}" | docker login -u "msinap" --password-stdin docker.io

      - name: Build and Push Docker image
        run: |
          docker build -t docker.io/msinap/video_search_inference_server:latest ./inference_server
          docker push docker.io/msinap/video_search_inference_server:latest

#      - name: Deploy to HamRavesh
