name: Inference_Server

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker registry
        run: echo "${{ secrets.HAMRAVESH_DOCKER_REGISTRY_PASSWORD }}" | docker login -u "mlsd-video-search" --password-stdin registry.hamdocker.ir/mlsd-video-search

      - name: Build and Push Docker image
        run: |
          docker build -t registry.hamdocker.ir/mlsd-video-search/video_search_inference_server:latest ./inference_server
          docker push registry.hamdocker.ir/mlsd-video-search/video_search_inference_server:latest

#      - name: Deploy to HamRavesh
