name: Inference_Server

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker registry
        run: echo "${{ secrets.DOCKER_REGISTRY_PASSWORD }}" | docker login -u "msinap" --password-stdin docker.io

      - name: Build and Push Docker image
        run: |
          docker build -t docker.io/msinap/video_search_inference_server:${{ github.sha }} ./inference_server
          docker push docker.io/msinap/video_search_inference_server:${{ github.sha }}

      - name: Install HamRavesh CLI
        run: |
          sudo apt install -y --no-install-recommends nodejs npm
          npm i g hamctl

      - name: Login to HamRavesh
        run: echo -ne '\n' | hamctl login -e m.sina.pakseresht@gmail.com -p "${{ secrets.HAMRAVESH_PASSWORD }}"

#      - name: Deploy to HamRavesh
#        run: hamctl apps set-image inference-server --image docker.io/msinap/video_search_inference_server --tag "${{ github.sha }}"
